# Generated by Django 5.0.6 on 2024-06-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis_client',
            name='telephone',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
