# Generated by Django 4.1.4 on 2024-09-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis_client',
            name='article',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devis_client',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devis_client',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devis_client',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='devis_client',
            name='noms_prenoms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devis_client',
            name='quantite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devis_client',
            name='telephone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newslettercontact',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='nom_complet',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='objet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
